apiVersion: v1
kind: Namespace
metadata:
  name: log-test
---
apiVersion: v1
kind: Pod
metadata:
  namespace: log-test
  name: logger
  labels:
    app: logger
    team: a-team
spec:
  terminationGracePeriodSeconds: 3
  containers:
    - image: alpine:3.2
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NORMAL_LOG
          value: '{ "stringTest":  "key", "intTest": 10, "floatTest": 1.2, "objectTest": "broken" }'
        - name: CLASHING_LOG
          value: '{ "stringTest":  "key", "intTest": 10, "floatTest": 1.2, "objectTest": {"key":  "value"} }'
        - name: TYPE_CLASH_LOG
          value: '{ "stringTest":  "key", "intTest": "broken", "floatTest": 1.2, "objectTest": {"key":  "value"} }'
      command: ["/bin/sh", "-ec","while true; do echo $NORMAL_LOG; echo $CLASHING_LOG; echo $TYPE_CLASH_LOG; sleep 30; end" ]
      imagePullPolicy: IfNotPresent
      name: alpine
  restartPolicy: Never
